name: Build Docker Image

on:
    push:
        branches:
            - main

env:
    USERNAME: vlsts
    IMAGE_NAME: tremend-devops-bv-int

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build-docker:
        runs-on: ubuntu-latest
        name: Build Docker Image
        steps:
          - name: Clone repository
            uses: actions/checkout@v4.2.2
    
          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v3.10.0

          - name: Login to Docker Hub
            uses: docker/login-action@v3.3.0
            with:
                username: ${{ env.USERNAME }}
                password: ${{ secrets.DOCKERHUB_PAT }}

          - name: Build docker image
            uses: docker/build-push-action@v6.13.0
            with:
              context: 2-docker/
              file: 2-docker/Dockerfile
              push: true
              tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
