name: Build Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-docker:
        runs-on: ubuntu-latest
        name: Build Docker Image
        steps:
          - name: Clone repository
            uses: actions/checkout@v4.2.2
    
          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v3.10.0

          - name: Login to Docker Hub
            uses: docker/login-action@v3.3.0
            with:
                username: vlsts
                password: ${{ secrets.DOCKERHUB_PAT }}

          - name: Build docker image
            uses: docker/build-push-action@v6.13.0
            with:
              context: 2-docker/
              file: 2-docker/Dockerfile
              push: true
              tags: vlsts/tremend-devops-bv-int:latest,vlsts/tremend-devops-bv-int:${{ github.sha }}
