# Name of the workflow
name: Build Docker Image

# When to trigger the workflow
on:
    # Trigger the workflow on any push event to the main branch whenever
    # the 2-docker directory or this workflow file is modified
    push:
        branches:
            - main
        paths: 
            - 2-docker/**
            - .github/workflows/build_docker.yml

# Environment variables to be used in the workflow
env:
    USERNAME: vlsts
    IMAGE_NAME: tremend-devops-bv-int

# Make sure only one instance of the workflow is running at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Jobs to be executed in the workflow
jobs:
    # Job to build the docker image
    # Runs on the latest version of Ubuntu available for GitHub Actions
    build-docker:
        runs-on: ubuntu-latest
        name: Build Docker Image
        steps:
          # Checkout the repository
          - name: Clone repository
            uses: actions/checkout@v4.2.2
    
          # Sets up Docker to be able to push images to Docker Hub
          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v3.10.0

          # Login to Docker Hub using the provided username and PAT stored in secrets
          - name: Login to Docker Hub
            uses: docker/login-action@v3.3.0
            with:
                username: ${{ env.USERNAME }}
                password: ${{ secrets.DOCKERHUB_PAT }}

          # Build the Docker image
          - name: Build docker image
            uses: docker/build-push-action@v6.13.0
            with:
              # Where to run docker from
              context: 2-docker/
              # Path to the Dockerfile
              file: 2-docker/Dockerfile
              # Should the image be pushed to Docker Hub
              push: true
              # Tags for the Docker image: latest and the commit SHA as requested
              tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
